application: typea-service
version: 1
runtime: python
api_version: 1

handlers:
- url: /js
  static_dir: js
  
- url: /css
  static_dir: css  

- url: /images
  static_dir: images

- url: /(.*\.(gif|png|jpg|ico))
  static_files: images/\1
  upload: static/(.*\.(gif|png|jpg|ico))
  
- url: /.*
  script: typea_service.py
